server:
  port: 8086 #记得修改端口号，防止冲突
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 # 这个跟feign无关
      http-method-specify: true # 开启请求方式前缀,便于区分不同接口
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启Feign对Sentinel支持
hm:
  swagger:
    title: 商品搜索接口文档
    package: com.hmall.search.controller
  db:
    database: hm-item
