server:
  port: 8084
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 # 这个跟feign无关
      http-method-specify: true # 开启请求方式前缀,便于区分不同接口
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  swagger:
    title: 用户管理服务接口文档
    package: com.hmall.user.controller
  db:
    database: hm-user
