server:
  port: 8085 #记得修改端口号，防止冲突
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 # 这个跟feign无关
      http-method-specify: true # 开启请求方式前缀,便于区分不同接口
hm:
  swagger:
    title: 交易服务接口文档
    package: com.hmall.trade.controller
  db:
    database: hm-trade
