server:
  port: 8086
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090 # 这个跟feign无关
      http-method-specify: true # 开启请求方式前缀,便于区分不同接口
feign:
  okhttp:
    enabled: true # 开启OKHttp连接池支持
  sentinel:
    enabled: true # 开启Feign对Sentinel支持
hm:
  swagger:
    title: 支付服务接口文档
    package: com.hmall.pay.controller
  db:
    database: hm-pay